name: market science
favicon: null
layout_spectrum: 0.9190125830937177
typography_spectrum: 0.7457662161905318
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#695d5f'
    - '#352c31'
    - '#aa9e95'
    - '#060404'
  brandStrength: 0.2705870233476162
  lightness: 0.8366145885083824
  saturation: 0.13266610633581877
  rhythmicContrast: 0.0883878325112164
purpose: []
